import { parseAmplifyConfig } from "aws-amplify/utils";

// `amplify_outputs.json` is generated by Amplify locally (`npx ampx sandbox`)
// and in Amplify Hosting CI/CD. Keep it in runtime app code only and out of
// build-time config such as `next.config.ts`.
import outputs from "@/amplify_outputs.json";

export const amplifyOutputs = outputs;
export const amplifyConfig = parseAmplifyConfig(outputs);
export const amplifyAuthConfig = outputs.auth;
export const amplifyStorageConfig = outputs.storage;
